import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'credit_card_details_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'credit_card_details_model.g.dart';

// class OnboardingState {
//   final AddressDetails addressDetails;

//   OnboardingState({required this.addressDetails});
// }

@freezed
class CreditCardDetails with _$CreditCardDetails {
  const factory CreditCardDetails(
      {required String cardNumber,
      required String expDate,
      required String cvv,
      required String country,
      required String zipCode,
      required String? creditCardType,
      required String nickName}) = _CreditCardDetails;

  factory CreditCardDetails.fromJson(Map<String, Object?> json) =>
      _$CreditCardDetailsFromJson(json);
}
