// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIRI286oTf7RSaIWlNt5uuNlmwTQO6SY',
    appId: '1:610338045611:web:1c1be00efa2052eebf41ee',
    messagingSenderId: '610338045611',
    projectId: 'uber-eats-clone-d792a',
    authDomain: 'uber-eats-clone-d792a.firebaseapp.com',
    storageBucket: 'uber-eats-clone-d792a.firebasestorage.app',
    measurementId: 'G-Q25LJ664H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqHLzRLiG7meM1SlfhmdHkh5w2TfV7bTM',
    appId: '1:610338045611:android:7ed8f677f02f1d18bf41ee',
    messagingSenderId: '610338045611',
    projectId: 'uber-eats-clone-d792a',
    storageBucket: 'uber-eats-clone-d792a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC78aNopt92Uo9418E8KkEQ1tzf8rAGPUQ',
    appId: '1:610338045611:ios:ebeb120d4c2a27edbf41ee',
    messagingSenderId: '610338045611',
    projectId: 'uber-eats-clone-d792a',
    storageBucket: 'uber-eats-clone-d792a.firebasestorage.app',
    iosBundleId: 'com.example.uberEatsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC78aNopt92Uo9418E8KkEQ1tzf8rAGPUQ',
    appId: '1:610338045611:ios:ebeb120d4c2a27edbf41ee',
    messagingSenderId: '610338045611',
    projectId: 'uber-eats-clone-d792a',
    storageBucket: 'uber-eats-clone-d792a.firebasestorage.app',
    iosBundleId: 'com.example.uberEatsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMIRI286oTf7RSaIWlNt5uuNlmwTQO6SY',
    appId: '1:610338045611:web:17c0c0461a5c1f66bf41ee',
    messagingSenderId: '610338045611',
    projectId: 'uber-eats-clone-d792a',
    authDomain: 'uber-eats-clone-d792a.firebaseapp.com',
    storageBucket: 'uber-eats-clone-d792a.firebasestorage.app',
    measurementId: 'G-SH0243P8T4',
  );
}
